name: Ejecutar pruebas

on:
  push:
    branches:
      - main

jobs:
  Ejecutar_tests:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout del c√≥digo 
      uses: actions/checkout@v2

    - name: Instalar Node.js y NPM
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm install  

    - name: Correr pruebas
      run: npm test
      
